repos:
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.10.5
      stages: [commit]
-   repo: local
    hooks:
      - id: requirements
        name: requirements
        entry: bash -c '.venv/bin/pip freeze > requirements.txt;'
        language: system
        pass_filenames: false
        stages: [commit]